### ISSUE TITLE
Regex to extract repo_url not quite right

### ISSUE THREAD

**Issue by robinbowes** [hayorov/terraform-init-booster#2]
The first time I run tf-init-booster in a directory, it fails:

```
$ tf-init-booster
2020-07-14 07:57:03,628	All modules: 187
2020-07-14 07:57:03,628	To download: 1
Traceback (most recent call last):
  File "/Users/robin/.pyenv/versions/td-terraform-3.7.1/bin/tf-init-booster", line 8, in <module>
    sys.exit(main())
  File "/Users/robin/.pyenv/versions/3.7.1/envs/td-terraform-3.7.1/lib/python3.7/site-packages/tf_init_booster/booster.py", line 103, in main
    clone_repo(repo)
  File "/Users/robin/.pyenv/versions/3.7.1/envs/td-terraform-3.7.1/lib/python3.7/site-packages/tf_init_booster/booster.py", line 84, in clone_repo
    git.Repo.clone_from(repo_url, module_path, branch=tag, depth=1)
  File "/Users/robin/.pyenv/versions/3.7.1/envs/td-terraform-3.7.1/lib/python3.7/site-packages/git/repo/base.py", line 1019, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/Users/robin/.pyenv/versions/3.7.1/envs/td-terraform-3.7.1/lib/python3.7/site-packages/git/repo/base.py", line 960, in _clone
    finalize_process(proc, stderr=stderr)
  File "/Users/robin/.pyenv/versions/3.7.1/envs/td-terraform-3.7.1/lib/python3.7/site-packages/git/util.py", line 328, in finalize_process
    proc.wait(**kwargs)
  File "/Users/robin/.pyenv/versions/3.7.1/envs/td-terraform-3.7.1/lib/python3.7/site-packages/git/cmd.py", line 408, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --branch=2.0.0 --depth=1 -v @github.com:treasure-data/terraform-aws-tfe_workspace.git .terraform/modules/terraform-aws-tfe_workspace_2.0.0
  stderr: 'Cloning into '.terraform/modules/terraform-aws-tfe_workspace_2.0.0'...
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]
           [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]
           [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
           [-i identity_file] [-J [user@]host[:port]] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] destination [command]
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

It seems that the regex to extract the repo_url is not quite right:

repo_uri: git@github.com:treasure-data/terraform-aws-tfe_workspace.git?ref=2.0.0
resulting repo_url: @github.com:treasure-data/terraform-aws-tfe_workspace.git

**Comment by hayorov** [comment]
Duplicate #1
